---
include:
  - project: "cocainefarm/templates/ci"
    file: "/rust.yaml"
  - project: "cocainefarm/templates/ci"
    file: "/tanka.base.yaml"

variables:
  RUST_RELEASE: "true"

build:container:tags:
  needs:
    - job: rust test
      optional: true
    - job: rust coverage
      optional: true
