[development]
address = "localhost"
port = 8000
keep_alive = 5
log = "normal"
storage_dir = "./storage"
database_dir = "./storage/db"
limits = { forms = 6710886400, png = 6710886400 }

[production]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log = "critical"
storage_dir = "./storage"
database_dir = "./storage/db"
limits = { forms = 6710886400 }
