#!/bin/env bash
fail() {
  printf '%s\n' "$1" >&2
  exit "${2-1}"
}

generate() {
  sass $1.scss $1.css || fail "install sass first"
  cat <(echo "/* Generated by $0 - do not edit manually */") $1.css > tmp.css
  mv tmp.css $1.css
}

generate main
